# Netlify configuration file for a Vite.js Single Page Application (SPA).

# The [build] block specifies the build settings.
[build]
  # This command is executed to build your site.
  command = "npm run build"

  # This is the directory that contains the built assets to be deployed.
  publish = "dist"

# The [[redirects]] block is crucial for SPAs.
# It ensures that any request that doesn't match a file in the "publish" directory
# is redirected to index.html. This allows your client-side router to handle the URL.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
